### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by SkyDonald** [abhiprojectz/gitrate#1]
I just added this to my repo and i have 100 likes and 62 dislikes

**Comment by abhiprojectz** [comment]
> I just added this to my repo and i have 100 likes and 62 dislikes

Its working try checking your repo twice and i just checked it.
https://github.com/SkyDonald/DeezerRPC

Now you have 102 likes and 62 dislikes.
Reply me asf , so i can close this issue :)

**Comment by SkyDonald** [comment]
Yes you can close this issue but before can you reset my repo in your database please I opened my repo yesterday it can't have 100 likes and 62 dislikes
